In [21]:
import numpy as np

In [22]:
def markov_chain(alpha):
    phi_bc = phi_ef = np.array([[0.9, 0.1], [0.1, 0.9]])
    psi_ab = psi_bd = psi_de = np.array([[alpha, 1-alpha], [1-alpha, alpha]])

    # marginal of e. Message propagates from f to e. f observed to be 0.
    m_ef_e = phi_ef.dot(np.array([[1.], [0.]]))
    # marginal of d. Message propagates from e to d.
    m_de_d = psi_de.dot(m_ef_e)
    #print(m_de_d)
    # marginal of b from d.
    m_bd_b = psi_bd.dot(m_de_d)
    #print(m_bd_b)
    # marginal of b from c. Message propagates from c to b. c observed to be 1.
    m_bc_b = phi_bc.dot(np.array([[0.], [1.]]))

    # marginal of a. Messages from 2 ways.
    m_ab_a = psi_ab.dot(m_bd_b * m_bc_b)
    #print(m_bd_b * m_bc_b)

    m_ab_a = m_ab_a / np.sum(m_ab_a)
    return m_ab_a

In [23]:
alpha = 0.99

marginal_a = markov_chain(alpha)
print(marginal_a)

[[0.45971599]
 [0.54028401]]


In [24]:
alpha = 0.9

marginal_a = markov_chain(alpha)
print(marginal_a)

[[0.30487805]
 [0.69512195]]


In [25]:
alpha = 0.6

marginal_a = markov_chain(alpha)
print(marginal_a)

[[0.42118227]
 [0.57881773]]
